language: node_js
sudo: false
dist: trusty
node_js:
  - lts/*
cache:
  directories:
    - './node_modules'
before_script:
  - yarn install
script:
  - yarn test
  - yarn build
  - 'yarn standard-version --releaseCommitMessageFormat="chore(release): {{currentTag}}\n\n[skip ci]"'
  - git push --follow-tags https://johnny-mh:$GH_TOKEN@github.com/johnny-mh/rxjs-shell.git master
deploy:
  provider: npm
  email: romz1212@gmail.com
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    repo: johnny-mh/rxjs-shell
